#!/bin/bash
#This Script generates C++ Classes
read -p "Enter Your Name: " username
read -p "Enter Your Class Name: " classname
read -p "Enter the Version of the Class: " versionnumber
read -p "Do You Want a NameSpace? [Y/N]: " want



if [ ${want} == "Y" ]
then
read -p " Please Enter Your NameSpace: " namespace
echo " Your Class is ${classname} and Your NameSpace is ${namespace} "
echo "/******************************************************************************
* @file:    ${classname}.hpp
* @author:  Copyright (c) `date +%Y` ${username}.  All rights reserved.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/
#ifndef _${classname}_H
#define _${classname}_H

namespace ${namespace}{
 
class ${classname}{

/* ==================================================================== */
/* ====================== Public Items of the Class =================== */
/* ==================================================================== */
public:
	// Class Constructors and Destructors go here
	${classname}();
	virtual ~${classname}();
	
	// Class Public Properties Methods go here
	

/* ==================================================================== */
/* ==================== Protected Items of the Class ================== */
/* ==================================================================== */
protected:
        //Class Protected Properties and Methods go here
        
	
/* ==================================================================== */
/* ===================== Private Items of the Class =================== */
/* ==================================================================== */	
private:
	//Class Private Properties and Methods go here
      
	  
};
 
}
#endif
" 1> ${classname}.hpp

echo "/******************************************************************************
* @file:    ${classname}.cpp
* @author:  Copyright (c) `date +%Y` ${username}.  All rights reserved.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/

/* ==================================================================== */
/* ========================== Include Files =========================== */
/* ==================================================================== */

#include \"${classname}.hpp\"

/* ==================================================================== */
/* ======================== Class Implementation ====================== */
/* ==================================================================== */
 
namespace ${namespace}{
 
	${classname}::${classname}(){}
       
        ${classname}::~${classname}(){}
       
}
" 1> ${classname}.cpp
clear
echo "Hello Mr: ${username} "
echo "Your Class was Created Correctly..... "

elif [ ${want} == "N" ]
then
echo "Your Class is ${classname} "
echo "/******************************************************************************
* @file:    ${classname}.hpp
* @author:  Copyright (c) `date +%Y` ${username}.  All rights reserved.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/
#ifndef _${classname}_H
#define _${classname}_H
 
class ${classname}{
 
/* ==================================================================== */
/* ====================== Public Items of the Class =================== */
/* ==================================================================== */
public:
	// Class Constructors and Destructors go here
	${classname}();
	virtual ~${classname}();
	
	// Class Public Properties Methods go here
	

/* ==================================================================== */
/* ==================== Protected Items of the Class ================== */
/* ==================================================================== */
protected:
        //Class Protected Properties and Methods go here
        
	
/* ==================================================================== */
/* ===================== Private Items of the Class =================== */
/* ==================================================================== */	
private:
	//Class Private Properties and Methods go here
      
	  
};
 
#endif
 
" 1> ${classname}.hpp

echo "/*****************************************************************************
* @file:    ${classname}.cpp
* @author:  Copyright (c) `date +%Y` ${username}.  All rights reserved.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
******************************************************************************/

/* ==================================================================== */
/* ========================== Include Files =========================== */
/* ==================================================================== */

#include \"${classname}.hpp\"
 
/* ==================================================================== */
/* ======================== Class Implementation ====================== */
/* ==================================================================== */ 

    ${classname}::${classname}(){}
       
    ${classname}::~${classname}(){}
       
 
" 1> ${classname}.cpp
clear
echo "Hello Mr: ${username} "
echo "Your Class was Created Correctly....."

fi



